[env:esp32-s3-devkitc-1]
platform = espressif32
board = rymcu-esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags = 
  -DARDUINO_ESP32_S3_DEV

board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs
board_build.sdkconfig_path = sdkconfig.defaults
board_build.arduino.memory_type = dio_opi  # S3N16R8 8MB Octal PSRAM

lib_deps = 
    https://github.com/T-vK/ESP32-BLE-Mouse.git
    bblanchon/ArduinoJson @ ^7.3.1